
image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - code_quality 
  - tests         # List of stages for jobs, and their order of execution
  - build
  - deploy

"Ensure PEP8-compliancy":
  stage: code_quality
  before_script:
    - python3 --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt

  script:
    - pycodestyle --ignore=E501 src/*.py

"Lint code with pylint":
  stage: code_quality
  before_script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - pylint --disable=R1705 src/*.py

"Run unit tests":
  stage: tests
  before_script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - pytest -v src/*.py 

"build-job":       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

"unit-test-job":   # This job runs in the test stage.
  stage: tests    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

"lint-test-job":   # This job also runs in the test stage.
  stage: tests    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

"deploy-job":      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
